### ISSUE TITLE
Sign Up Box

### ISSUE THREAD

**Issue by moyales** [moyales/Cheap-n-Ease#2]
Having trouble trying to put the sign up box on the right side of the navbar area. Most likely a problem with the CSS in cne-styling.css, but I could be entirely wrong.

**Comment by WBot3000** [comment]
I basically put the whole bar in a div tag and then resized it to take up the entire width of the screen. Basically, the problem was that "float: right;" wasn't doing anything b/c the signup box was already as right as it could be (the list did not take up the whole bar, just the portion it was using)
